print("Hello World!.")
print("Welcome to python programming")
print("my name is jaswanth")
print("I am learniing python programming")
print("I am very happy to learn python programming")
print("good afternoon")
print("welcome to python programming")
print("python is a logical programming language")
print("python is a simple programming language")
print("my first program in python programminglanguage")
print("Hello from python programming")